version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
        - cesium

sphinx:
  # fail_on_warning: true  # Too hard, maybe one day?
  fail_on_warning: false
