package:
  name: poliastro
  version: "0.5.0"

source:
  git_url: https://github.com/poliastro/poliastro
  git_tag: v0.5.0

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - numpy >=1.9
    - scipy
    - numba >=0.23
    - astropy >=1.0
    - jplephem
    - matplotlib

test:
  imports:
    - poliastro
    - poliastro.twobody

  requires:
    - pytest

about:
  home: https://poliastro.github.io/
  license: MIT License
  summary: "Python package for Orbital Mechanics"
